name: Java CI with Gradle # CI 이름 (기본적으로 Gradle을 사용한 Java 프로젝트 빌드)

on:
  push:
    branches: [ "master" ] # master 브랜치로 푸시될 때마다 실행
  pull_request:
    branches: [ "master" ] # master 브랜치로의 풀 리퀘스트가 열릴 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 (Ubuntu 최신 버전)

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432 # 포트 매핑
        env:
          POSTGRES_USER: sa  # PostgreSQL 사용자
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}  # GitHub Secrets에서 비밀번호 가져오기
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -Dspring.profiles.active=postgres
